version: 2.0
jobs: 
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: 
          name: change directory
          command: cd App.Tests/
      - run:
          name: Restore Packages of App.Tests
          command: dotnet restore
      - run:
          name: Build App.Tests
          command: dotnet build
      - run:
          name: Test App.Tests
          command: dotnet test